name: Go

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'image tag'     
        required: true

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build binary
      run: go build -v -a -tags netgo -o release/linux/amd64/drone-github-release ./cmd/drone-github-release
    
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: name/app
   
    - name: Build image
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64
        file: docker/Dockerfile.linux.amd64
        labels: ${{ steps.meta.outputs.labels }}



